Update pr-lint.yml

diff --git a/.github/workflows/pr-lint.yml b/.github/workflows/pr-lint.yml
--- a/.github/workflows/pr-lint.yml
+++ b/.github/workflows/pr-lint.yml
@@ -17,6 +17,10 @@ jobs:
           )
           pr_description_escaped=$(printf "%s" "$pr_description" | sed 's/"/\\\"/g')
           echo $pr_description_escaped
+          if ! echo "$pr_description_escaped" | grep -Eq '## Description|## Jira Links|## Changes Made'; then
+            echo "PR description is missing one or more these required headings: ## Description|## Jira Links|## Changes Made"
+            exit 1
+          fi
           if echo "$pr_description_escaped" | awk 'BEGIN { RS = "" } /## Description[[:space:]]+(.*)[[:space:]]+## Jira Links/ {
               match($0, /## Description[[:space:]]+(.*)[[:space:]]+## Jira Links/, arr);
               gsub(/^[[:space:]]+|[[:space:]]+$/, "", arr[1]);
